### ISSUE TITLE
Get Uint256 and Int256 up to stdlib number standards.

### ISSUE THREAD

**Issue by jtremback** [althea-mesh/num256_rs#3]
They should work in the exact same way as stdlib numbers. However, there may be some methods we are ok skipping for now such as bit shifting stuff. Talk to Jehan to review what to implement before starting.

**Comment by jkilpatr** [comment]
ok what we need here are all the traits std provides for both numbers (and none standard does not provide) and then a review and removal of .add() etc in our codebases
